#!/bin/sh

if [ ! -d .build/gyb ]; then
	echo -n Downloading gyb
	mkdir -p .build/gyb
	curl -s https://raw.githubusercontent.com/apple/swift/master/utils/gyb > .build/gyb/gyb
	curl -s https://raw.githubusercontent.com/apple/swift/master/utils/gyb.py > .build/gyb/gyb.py
	chmod 755 .build/gyb/gyb
	echo -e "\t[done]"
fi

for f in Sources/Perl/Call.swift Sources/Perl/CV.swift; do
	echo -n $f
	.build/gyb/gyb $f.gyb > $f
	echo -e "\t[done]"
done
