#!/usr/bin/perl

use strict;
use warnings;
use FindBin;

my $root = $FindBin::Bin;

expand_gyb();

sub expand_gyb {
	unless (-d ".build/gyb") {
		system("mkdir -p .build/gyb") == 0
			or die "Cannot mdkir .build/gyb";
		foreach my $f (qw/ gyb gyb.py /) {
			system("curl -f -s https://raw.githubusercontent.com/apple/swift/master/utils/$f -o .build/gyb/$f") == 0
				or die "Failed to download gyb";
		}
		chmod 0755, ".build/gyb/gyb" or die $!;
	}

	foreach my $f (qw# Sources/Perl/Call.swift Sources/Perl/Subroutine.swift #) {
		my $filename = "$root/$f";
		system(".build/gyb/gyb $filename.gyb > $filename.tmp") == 0
			or die "Failed to expand gyb template\n";
		commit_file($filename);
	}
}

sub commit_file {
	my ($filename) = @_;
	if (system("cmp -s $filename.tmp $filename") == 0) {
		unlink "$filename.tmp" or die $!;
	} else {
		rename "$filename.tmp", $filename or die $!;
	}
	return;
}
